################################################################################
#
#   Orderer Configuration
#
#   - This controls the type and configuration of the orderer.
#
################################################################################
General:
    # Listen address: The IP on which to bind to listen.
    ListenAddress: 127.0.0.1     # localhost for dev
    # Listen port: The port on which to bind to listen.
    ListenPort: 7050

    # TLS: TLS settings for the GRPC server.
    TLS:
        # Require server-side TLS
        Enabled: true
        # PrivateKey governs the file location of the private key of the TLS certificate.
        PrivateKey: /home/hyperdev/git/Maori-Hyperledger/test-network/organizations/ordererOrganizations/Maori-orderer.blockchain.maori/tls/server.key
        # Certificate governs the file location of the server TLS certificate.
        Certificate: /home/hyperdev/git/Maori-Hyperledger/test-network/organizations/ordererOrganizations/Maori-orderer.blockchain.maori/tls/server.crt
        # RootCAs contains a list of additional root certificates used for verifying certificates of other orderer nodes during outbound connections.
        RootCAs:
          - /home/hyperdev/git/Maori-Hyperledger/test-network/organizations/ordererOrganizations/Maori-orderer.blockchain.maori/tls/ca.crt
        # Require client certificates / mutual TLS for inbound connections.
        ClientAuthRequired: false
        ClientRootCAs:

    # Keepalive settings for the GRPC server.
    Keepalive:
        # ServerMinInterval is the minimum permitted time between client pings.
        # If clients send pings more frequently, the server will
        # disconnect them.
        ServerMinInterval: 60s
        # ServerInterval is the time between pings to clients.
        ServerInterval: 7200s
        # ServerTimeout is the duration the server waits for a response from
        # a client before closing the connection.
        ServerTimeout: 20s

    # Max message size in bytes the GRPC server and client can receive
    MaxRecvMsgSize: 104857600
    # Max message size in bytes the GRPC server and client can send
    MaxSendMsgSize: 104857600

    # Bootstrap method: The method by which to obtain the bootstrap block
    # system channel is specified. The option can be one of:
    #   "file" - path to a file containing the genesis block or config block of system channel
    #   "none" - allows an orderer to start without a system channel configuration
    BootstrapMethod: file

    # Bootstrap file: The file containing the bootstrap block to use when initializing the orderer system channel 
    BootstrapFile: /home/hyperdev/git/Maori-Hyperledger/test-network/configtxgen/waka-genesis.block

    # LocalMSPDir is where to find the private crypto material needed by the orderer. 
    LocalMSPDir: /home/hyperdev/git/Maori-Hyperledger/test-network/organizations/ordererOrganizations/Maori-orderer.blockchain.maori/msp

    # LocalMSPID is the identity to register the local MSP material with the MSP manager. IMPORTANT: The local MSP ID of an orderer needs to match the MSP
    # ID of one of the organizations defined in the orderer system channel's /Channel/Orderer configuration. 
    LocalMSPID: Maori-orderer

    # BCCSP configures the blockchain crypto service providers.
    BCCSP:
        # Default specifies the preferred blockchain crypto service provider to use. 
        Default: SW
        # SW configures the software based blockchain crypto provider.
        SW:
            # TODO: The default Hash and Security level needs refactoring to be
            # fully configurable. Changing these defaults requires coordination
            # SHA2 is hardcoded in several places, not only BCCSP
            Hash: SHA2
            Security: 256
            # Location of key store. If this is unset, a location will be
            # chosen using: 'LocalMSPDir'/keystore
            FileKeyStore:
                KeyStore:

    # Authentication contains configuration parameters related to authenticating client messages
    Authentication:
        # the acceptable difference between the current server time and the client's time as specified in a client request message
        TimeWindow: 15m

################################################################################
#
#   SECTION: File Ledger
#
#   - This section applies to the configuration of the file ledger.
#
################################################################################
FileLedger:

    # Location: The directory to store the blocks in.
    Location: ../ledgers/orderer/maori-blockchain/ledger

################################################################################
#
#   Operations Configuration
#
#   - This configures the operations server endpoint for the orderer
#
################################################################################
Operations:
    # host and port for the operations server
    ListenAddress: 127.0.0.1:8443
    # TLS configuration for the operations endpoint
    TLS:
        # TLS enabled
        Enabled: false

################################################################################
#
#   Metrics Configuration
#
#   - This configures metrics collection for the orderer
#
################################################################################
Metrics:
    # The metrics provider is one of statsd, prometheus, or disabled
    Provider: disabled

################################################################################
#
#   Admin Configuration
#
#   - This configures the admin server endpoint for the orderer
#
################################################################################
Admin:
    # host and port for the admin server
    ListenAddress: 127.0.0.1:9443

    # TLS configuration for the admin endpoint
    TLS:
        # TLS enabled
        Enabled: false

################################################################################
#
#   Channel participation API Configuration
#
#   - This provides the channel participation API configuration for the orderer.
#   - Channel participation uses the ListenAddress and TLS settings of the Admin
#     service.
#
################################################################################
ChannelParticipation:
    # Channel participation API is enabled.
    Enabled: false

################################################################################
#
#   Consensus Configuration
#
#   - This section contains config options for a consensus plugin. It is opaque to orderer, and completely up to consensus implementation to make use of.
#
################################################################################
Consensus:
    # The allowed key-value pairs here depend on consensus plugin. For etcd/raft, we use following options:

    # WALDir specifies the location at which Write Ahead Logs for etcd/raft are stored. Each channel will have its own subdir named after channel ID.
    WALDir: /home/hyperdev/git/Maori-Hyperledger/test-network/organizations/ordererOrganizations/Maori-orderer/etcdraft/wal

    # SnapDir specifies the location at which snapshots for etcd/raft are stored. Each channel will have its own subdir named after channel ID.
    SnapDir: /home/hyperdev/git/Maori-Hyperledger/test-network/organizations/ordererOrganizations/Maori-orderer/etcdraft/snapshot
